### ISSUE TITLE
預設文字顏色問題

### ISSUE THREAD

**Issue by stylelinz** [wlcharlie/One#1]
目前文字顏色預設為白色，跟背景顏色一樣導致無法看清文字

<img width="768" alt="圖片" src="https://github.com/wlcharlie/One/assets/69614421/5b986d7f-48ca-4aad-954a-96f0822317a7">

**Comment by wlcharlie** [comment]
收

**Comment by wlcharlie** [comment]
自己給自己ＰＲ
